### ISSUE TITLE
Can't load in folia 1.20.2

### ISSUE THREAD

**Issue by ddsb520** [ocelotpotpie/FreedomChat#48]
**Log**
[18:34:29 INFO]: [FreedomChat] Enabling FreedomChat v1.5.1
[18:34:29 ERROR]: Error occurred while enabling FreedomChat v1.5.1 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/core/IRegistryCustom
        at ru.bk.oharass.freedomchat.FreedomChat.onEnable(FreedomChat.java:25) ~[FreedomChat-1.5.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:652) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:563) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:343) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.core.IRegistryCustom
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        ... 13 more
[18:34:29 INFO]: [FreedomChat] Disabling FreedomChat v1.5.1
**Freedom Chat Version**
1.5.1

**Comment by e-im** [comment]
You're using Mojang mapped Folia. This will cause any plugin expecting spigot mappings not to work.

While Mojang mappings at runtime are the future for Paper, for the moment you are mostly on your own running them and expected to be an advanced user.

If you did not intend to run Mojang mappings, you failed while compiling Folia. Use the jar produced with a `-reobf` suffix.

If you intended to use Mojang mappings, then you will need to compile FreedomChat yourself and use the jar suffixed with `-dev-all.jar`.
