### ISSUE TITLE
[Folia] Error while enabling FreedomChat v1.7.0

### ISSUE THREAD

**Issue by TheJoshue** [ocelotpotpie/FreedomChat#62]
Hello there,

I assume that this happens because v1.7.0 of the plugin is compatible for 1.21 and not 1.21.1 which i am running?
But i am also in doubt because the filename is `FreedomChat-Paper-1.7.0` and there is no `Folia` version of the .jar, but i am still unsure if i am missing to find the folia jar maybe, or it is because my server is 1.21.1 but plugin supports only 1.21 actually?

I am running very latest Folia 1.21.1-R0.1-SNAPSHOT, self compiled (but i forked it to compile it so it might not show correct commit number if it's included in `/ver` command, just to mention that)

Version output:
```
This server is running Folia version 1.21.1-DEV-dev/1.21.1@1289172 (2024-10-05T09:50:46Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
Unknown version
```

Here is the error

```
[12:42:54 ERROR]: Error occurred while enabling FreedomChat v1.7.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/network/chat/Component
        at FreedomChat-Paper-1.7.0.jar/ru.bk.oharass.freedomchat.FreedomChat.onEnable(FreedomChat.java:27) ~[FreedomChat-Paper-1.7.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[folia-1.21.1.jar:1.21.1-DEV-1289172]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[folia-1.21.1.jar:1.21.1-DEV-1289172]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:646) ~[?:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:595) ~[?:?]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:780) ~[folia-1.21.1.jar:1.21.1-DEV-1289172]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:527) ~[folia-1.21.1.jar:1.21.1-DEV-1289172]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[folia-1.21.1.jar:1.21.1-DEV-1289172]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1281) ~[folia-1.21.1.jar:1.21.1-DEV-1289172]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:357) ~[folia-1.21.1.jar:1.21.1-DEV-1289172]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.network.chat.Component
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 13 more
```

Thank you in advance for answers!

**Comment by TheJoshue** [comment]
> You are using spigot mapped folia. Paper 1.21+ ships with Mojang mappings by default which FreedomChat uses.

i have paperclip and bundler jar
i used paperclip one, should i use bundler?

**Comment by TheJoshue** [comment]
I switched to bundler jar
The issue still happens
```
[02:48:12 INFO]: [FreedomChat] Enabling FreedomChat v1.7.0
[02:48:12 ERROR]: Error occurred while enabling FreedomChat v1.7.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/network/chat/Component
        at FreedomChat-Paper-1.7.0.jar/ru.bk.oharass.freedomchat.FreedomChat.onEnable(FreedomChat.java:27) ~[FreedomChat-Paper-1.7.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[folia-1.21.1.jar:1.21.1-DEV-1289172]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[folia-1.21.1.jar:1.21.1-DEV-1289172]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:646) ~[?:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:595) ~[?:?]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:780) ~[folia-1.21.1.jar:1.21.1-DEV-1289172]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:527) ~[folia-1.21.1.jar:1.21.1-DEV-1289172]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[folia-1.21.1.jar:1.21.1-DEV-1289172]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1281) ~[folia-1.21.1.jar:1.21.1-DEV-1289172]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:357) ~[folia-1.21.1.jar:1.21.1-DEV-1289172]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.network.chat.Component
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 13 more
```

**Comment by TheJoshue** [comment]
> You are using spigot mapped folia. Paper 1.21+ ships with Mojang mappings by default which FreedomChat uses.

I'm sorry, how to get paper mapped folia?

**Comment by TheJoshue** [comment]
> compile with `./gradlew createMojmapBundlerJar` rather than `./gradlew createReobfBundlerJar`

I initially tried using this createMojmapBundlerJar because that's what's stated in readme of papermc folia repo, however it constantly gave me 2 files both within range of 20-25mb which did not want to start for error i forgot what it said...
Somehow, i tried this `./gradlew createMojmapBundlerJar` again and... it generated mojmap ~80mb file, idk why it did not generate it in the first place.

All in all, it works now, thank you very much
