### ISSUE TITLE
Fabric server fails to start when ServerCore is installed

### ISSUE THREAD

**Issue by n1ckoates** [ocelotpotpie/FreedomChat#68]
When starting a server with ServerCore and FreedomChat installed, it immediately stops with this error:
```
[10:07:10] [main/ERROR]: Uncaught exception in thread "main"
java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:71) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.21.3-loader.0.16.9-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.server.Main failed
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:473) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.16.9.jar:?]
        ... 1 more
Caused by: java.lang.NoSuchMethodError: 'void org.yaml.snakeyaml.DumperOptions.setProcessComments(boolean)'
        at knot/me.wesley1808.servercore.common.config.ConfigManager.lambda$create$0(ConfigManager.java:43) ~[servercore-fabric-1.5.8+1.21.3.jar:?]
        at knot/space.arim.dazzleconf.ext.snakeyaml.SnakeYamlConfigurationFactory.loadMapFromReader(SnakeYamlConfigurationFactory.java:131) ~[space_arim_dazzleconf_dazzleconfml-1.3.0-M2-be20db82564942fd.jar:?]
        at knot/space.arim.dazzleconf.factory.AbstractConfigurationFactory$ConfigFactoryDelegate.loadMap(AbstractConfigurationFactory.java:148) ~[space_arim_dazzleconf_dazzleconfre-1.3.0-M2-ef80c55a5f97069b.jar:?]
        at knot/space.arim.dazzleconf.factory.HumanReadableConfigurationFactory.bufferedLoadMap(HumanReadableConfigurationFactory.java:90) ~[space_arim_dazzleconf_dazzleconfre-1.3.0-M2-ef80c55a5f97069b.jar:?]
        at knot/space.arim.dazzleconf.factory.HumanReadableConfigurationFactory.loadMap(HumanReadableConfigurationFactory.java:78) ~[space_arim_dazzleconf_dazzleconfre-1.3.0-M2-ef80c55a5f97069b.jar:?]
        at knot/space.arim.dazzleconf.factory.ConfigurationFormatFactory.load(ConfigurationFormatFactory.java:126) ~[space_arim_dazzleconf_dazzleconfre-1.3.0-M2-ef80c55a5f97069b.jar:?]
        at knot/space.arim.dazzleconf.factory.DelegatingConfigurationFactory.load(DelegatingConfigurationFactory.java:57) ~[space_arim_dazzleconf_dazzleconfre-1.3.0-M2-ef80c55a5f97069b.jar:?]
        at knot/space.arim.dazzleconf.factory.AbstractConfigurationFactory.load(AbstractConfigurationFactory.java:42) ~[space_arim_dazzleconf_dazzleconfre-1.3.0-M2-ef80c55a5f97069b.jar:?]
        at knot/me.wesley1808.servercore.common.config.ConfigManager.reloadConfigData(ConfigManager.java:106) ~[servercore-fabric-1.5.8+1.21.3.jar:?]
        at knot/me.wesley1808.servercore.common.config.ConfigManager.reload(ConfigManager.java:67) ~[servercore-fabric-1.5.8+1.21.3.jar:?]
        at knot/me.wesley1808.servercore.common.config.Config.loadOptimizationConfig(Config.java:25) ~[servercore-fabric-1.5.8+1.21.3.jar:?]
        at knot/me.wesley1808.servercore.mixin.ServerCoreMixinPlugin.onLoad(ServerCoreMixinPlugin.java:18) ~[servercore-fabric-1.5.8+1.21.3.jar:?]
        at org.spongepowered.asm.mixin.transformer.PluginHandle.onLoad(PluginHandle.java:119) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:790) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:473) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.16.9.jar:?]
```

Also reported this issue on ServerCore's issue tracker: https://github.com/Wesley1808/ServerCore/issues/122

**Comment by pop4959** [comment]
Fixed on FreedomChat's end in a2539c2. ServerCore should also fix this on their end as it looks like they are not relocating either, which means that they will continue to have this issue with any other mods that aren't relocating properly.
